#!/usr/bin/env python3
#
# Translated from the Bash script `checkout-keystore.orig`.
#
# "TODO" comments mark things that could be improved in Pysh.

import os
import sys
import time

import click
from pysh import check_cmd, slurp_cmd, try_cmd


@click.command()
def main():
    # TODO careful with fsdecode/fsencode in the right places
    rootdir = os.fsdecode(slurp_cmd('git rev-parse --show-toplevel'))
    cleartext = f'{rootdir}/android/release.keystore'
    cryptotext = f'{rootdir}/android/release.keystore.gpg'

    check_cmd('gpg -d -o {} {}', cleartext, cryptotext)  # TODO f-style

    wait_min = 15
    # This pattern translates `( ... ) &` -- pretty exactly, I think!
    # Specifically the `if os.fork() == 0: ... sys.exit(0)`.
    # TODO provide as perhaps a context manager?
    if os.fork() == 0:
        time.sleep(wait_min * 60)
        try_cmd('rm -f {}', cleartext)  # TODO f-style
        sys.exit(0)

    print(f'''
Wrote decrypted file: {cleartext}

This file will be deleted in {wait_min} minutes.
''', file=sys.stderr)


if __name__ == '__main__':
    main()
